### ISSUE TITLE
Add configuration of averaging

### ISSUE THREAD

**Issue by rnestler** [Sensirion/embedded-sfm#10]

**Comment by nathanaelg** [comment]
I believe your datasheet might be wrong? https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/5_Mass_Flow_Meters/Datasheets/Sensirion_Mass_Flow_Meters_SFM3019_Datasheet.pdf

![image](https://user-images.githubusercontent.com/2712036/120271394-5d23ac00-c2ff-11eb-9519-f1e8047b6757.png)

Seems like the bit for averaging type is 1 for fixed-N and 0 for average-until-read

**Comment by rnestler** [comment]
Hi @nathanaelg 

Thanks for the notice! I forwarded it accordingly, since I'm not sure about it.

**Comment by rnestler** [comment]
The datasheet has been fixed and the fixed version will be published soon.

**Comment by rnestler** [comment]
@nathanaelg The fix has been published in the meantime, thanks again for reporting :slightly_smiling_face:

**Comment by MBjoern** [comment]
There will be new embedded, arduino and raspberry pi drivers coming soon, allowing to use the entire feature set described in the SF06 based sensor data sheets.

I'll be closing this issue accordingly.
