### ISSUE TITLE
Verify product number on probe

### ISSUE THREAD

**Issue by rnestler** [Sensirion/embedded-sfm#13]
Currently we just check if a device on the I2C address accepts the read product identifier command, but don't verify if it is the correct product.

**Comment by abrauchli** [comment]
IMHO that should be optional. Embedded drivers are not the typical plug-and-play drivers, but for an arduino wrapper it might make sense, e.g. we have auto-probing for arduino-sht

**Comment by rnestler** [comment]
It also allows to detect other problems, for example if the sensor is still in measurement mode. It will then return garbage for the product identification.

**Comment by MBjoern** [comment]
There will be new embedded, arduino and raspberry pi drivers coming soon, allowing to use the entire feature set described in the SF06 based sensor data sheets.

I'll be closing this issue accordingly.
