### ISSUE TITLE
SFM3000 

### ISSUE THREAD

**Issue by MrGhali** [Sensirion/embedded-sfm#17]
Is there a source for working the SFM3000 and get a digital read for the flow in LCD using arduino ?

**Comment by rnestler** [comment]
Not in this repository as of now. A quick search showed up https://github.com/dwerne/Sensirion_SFM3000_arduino but I never used that code, so I'm not sure if it will work for you :slightly_smiling_face:  

For more official sources on how to work with the SFM3000 check out https://www.sensirion.com/en/download-center/mass-flow-meters/low-pressure-drop-mass-flow-meter/. Especially the [Sample Code Source](https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/5_Mass_Flow_Meters/Software/Sensirion_Gas_Flow_SFM3000_Sample_Code_Source_V1.2.zip).
