### ISSUE TITLE
sfm3019

### ISSUE THREAD

**Issue by orelorel6** [Sensirion/embedded-sfm#18]
im try to use the sample and i got erro like (i install the library):

libraries\sfm3019-0.1.0\sensirion_common.c.o: In function `sensirion_i2c_general_call_reset':

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sensirion_common.c:68: undefined reference to `sensirion_i2c_write'

libraries\sfm3019-0.1.0\sensirion_common.c.o: In function `sensirion_i2c_read_words_as_bytes':

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sensirion_common.c:99: undefined reference to `sensirion_i2c_read'

libraries\sfm3019-0.1.0\sensirion_common.c.o: In function `sensirion_i2c_write_cmd':

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sensirion_common.c:138: undefined reference to `sensirion_i2c_write'

libraries\sfm3019-0.1.0\sensirion_common.c.o: In function `sensirion_i2c_write_cmd_with_args':

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sensirion_common.c:148: undefined reference to `sensirion_i2c_write'

libraries\sfm3019-0.1.0\sensirion_common.c.o: In function `sensirion_i2c_delayed_read_cmd':

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sensirion_common.c:158: undefined reference to `sensirion_i2c_write'

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sensirion_common.c:163: undefined reference to `sensirion_sleep_usec'

libraries\sfm3019-0.1.0\sfm3019_example_usage.c.o: In function `main':

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sfm3019_example_usage.c:46: undefined reference to `sensirion_i2c_init'

C:\Users\orel ezra\Documents\Arduino\libraries\sfm3019-0.1.0/sfm3019_example_usage.c:54: undefined reference to `sensirion_sleep_usec'

collect2.exe: error: ld returned 1 exit status

exit status 1

**Comment by rnestler** [comment]
Hi @orelorel6 
Which Arduino version are you using? Also did you see the Arduino example at https://github.com/Sensirion/embedded-sfm/tree/master/sample-projects/sfm3019-arduino?

**Comment by orelorel6** [comment]
Im try uno and doe
This is the script i run
And this was the error i get

בתאריך יום ג׳, 2 ביוני 2020, 0:21, מאת Raphael Nestler ‏<
notifications@github.com>:

**Comment by psachs** [comment]
Hi @orelorel6 

You are missing the dependencies for the SFM3019 drivers. I recommend you download the release package for SFM3019 from her:
https://github.com/Sensirion/embedded-sfm/releases

The sample project @rnestler mentioned does not include the driver code.  Create a library folder for the SFM driver with all required c/h files in it and copy it to the Arduino driver folder.

You also have to implement the i2c interface, there are sample implementations for Arduino in the release package

**Comment by psachs** [comment]
Hi @orelorel6 

Find attached the arduino library based on current master of sfm3019 driver (since the sample project uses code from master)

Unzip this and copy it to your arduino library folder, afterwards your project should compile. Depending on the arduino and I2C you are using for the sensor you might have to adjust  `sensirion_hw_i2c_implementation.cpp`

[arduino-sfm3019-lib.zip](https://github.com/Sensirion/embedded-sfm/files/4715255/arduino-sfm3019-lib.zip)

**Comment by rnestler** [comment]
@orelorel6 We just released 0.1.1 which includes the Arduino example project: https://github.com/Sensirion/embedded-sfm/releases/tag/0.1.1

**Comment by rnestler** [comment]
@orelorel6 Is this still active? Otherwise I'll close the issue.

**Comment by orelorel6** [comment]
Its work now
Thanks

בתאריך יום ד׳, 10 ביוני 2020, 10:13, מאת Raphael Nestler ‏<
notifications@github.com>:

**Comment by rnestler** [comment]
Awesome!
