### ISSUE TITLE
Add integer conversion functions

### ISSUE THREAD

**Issue by rnestler** [Sensirion/embedded-sfm#6]
Currently we convert the raw measurements to floats. We should provide a way to convert to `int32_t` with mili degree Celsius and mili "flow unit" without using floating point math.

**Comment by MBjoern** [comment]
There will be new embedded, arduino and raspberry pi drivers coming soon, allowing to use the entire feature set described in the SF06 based sensor data sheets.

I'll be closing this issue accordingly.
